api:
  image: mikamboo/devbox
  volumes:
   - .:/app
  links:
   - db:db
  ports:
   - "3000:3000"
   - "35729:35729"
db:
  image: mongo
  ports:
   - "27017:27017"

ionic:
  image: mikamboo/ionic-box
  privileged: true
  working_dir: /app
  volumes: 
    - /home/mikamboo/box/lpdj/lpdj-mobile-public:/app 
    - /dev/bus/usb:/dev/bus/usb
  ports: 
    - 9222:9222
    - 8100:8100 
    - 35730:35729 

